---

- hosts: all
  gather_facts: no
  tasks:
  - name: install python if missing
    raw: test -e /usr/bin/python || apt-get -y install python
    register: output
    changed_when: output.stdout != ""
